name: Build Plugin

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC (Compilador nativo)
      uses: ilammy/msvc-dev-cmd@v1

    - name: Download ArkServerAPI SDK (Espejo Público)
      run: |
        curl -L -o api.zip "https://github.com/skp90/Ark-Server-API/archive/refs/heads/master.zip"
        tar -xf api.zip
        rename Ark-Server-API-master ArkApi
        
    - name: Compile DLL Directo
      run: |
        cl.exe /LD /O2 /EHsc /I"ArkApi/Header" TekBowFix.cpp /link /LIBPATH:"ArkApi/Lib" ArkServerApi.lib /OUT:TekBowFix.dll
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TekBowFix-Binario
        path: TekBowFix.dll
