name: Build Plugin

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC (Compilador nativo)
      uses: ilammy/msvc-dev-cmd@v1

    - name: Download ArkServerAPI SDK
      shell: powershell
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri "https://github.com/skp90/Ark-Server-API/archive/refs/heads/master.zip" -OutFile "api.zip"
        Expand-Archive -Path "api.zip" -DestinationPath "."
        Rename-Item -Path "Ark-Server-API-master" -NewName "ArkApi"
        
    - name: Compile DLL Directo
      run: |
        cl.exe /LD /O2 /EHsc /I"ArkApi/Header" TekBowFix.cpp /link /LIBPATH:"ArkApi/Lib" ArkServerApi.lib /OUT:TekBowFix.dll
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TekBowFix-Binario
        path: TekBowFix.dll
